Test which attempts to log in with different combinations of credentials
Zoltekk/Testing-project pull request #3
Opened 2023-01-24 23:44 UTC by Zoltekk

Test which attempts to log in with different combinations of credentials and checks whether it was a successful attempt or not

2023-01-25 21:00 UTC, Glovacky requested changes

2023-01-25 21:00 UTC, Glovacky commented on task1/config.json
> +  },
Since you're not loading credentials from this file you should remove them.

2023-01-25 21:00 UTC, Glovacky commented on task1/conftest.py
> +    return data["credentials"]
It seems you don't need this fixture anymore

2023-01-26 01:42 UTC, Zoltekk commented on task1/config.json
> +  },
Removed

2023-01-26 01:42 UTC, Zoltekk commented on task1/conftest.py
> +    return data["credentials"]
Removed

2023-01-26 14:21 UTC, Glovacky approved these changes
Good job.

2023-01-26 15:50 UTC, merged